### ISSUE TITLE
security patch required

### ISSUE THREAD

**Issue by cemachelen** [cemac/jupyterhub_on_azure#5]
!--- These lines "< !-- -- >" are comment line to help you fill out the bug report, they will not appear in the report  -->

## Expected Behavior

Working fine

## Current Behavior

Vulnerability detected in jupyter hub and notebook

## Possible Solution

1. https://jupyterhub.readthedocs.io/en/stable/reference/upgrading.html
2. **NB** requires downtime

## Steps to Reproduce (for bugs)

none

## Context

security fix

## Your Environment

* Python version:
* Operating System and version (UNIX strongly recommended):

**Comment by andreww** [comment]
From my point of view, it would be good to do this before Easter. Most of the students are away on fieldwork next week (as am I) so I would be very surprised if anybody notices downtime then. 

Longer term, there are two weeks of teaching left (29/4/2019 - 10/5/2019) so shutting the server and VM down at the end of the week after that would be fine. Students (and I) only need a week or so of access after the end of the module on 10/5/2019 to download anything they want in future.

**Comment by cemachelen** [comment]
Thanks, I'll schedule to do this for next Friday morning then.  The vulnerability is only "moderate severity" and exists on all Jupyter notebook servers including personal versions so there's not too much worry on it. 

Thanks for the update on times. I have a meeting with Martyn at some point about me and/or Richard moving this to a containerised system for next year so we will probably keep it live for a bit longer in May in order to have a play around after you're done!
